In [1]:
import numpy as np

#a. Store the input and filter using NumPy arrays.
# Input matrix
input_matrix = np.array([
    [1, 1, 1, 0, 0],
    [0, 1, 1, 1, 0],
    [0, 0, 1, 1, 1],
    [0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0]
])

# Filter (kernel)
filter_matrix = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])

# Parameters
stride = 1
padding = 0

In [2]:
input_rows, input_cols = input_matrix.shape
filter_rows, filter_cols = filter_matrix.shape

In [3]:
output_rows = ((input_rows - filter_rows + 2 * padding) // stride) + 1
output_cols = ((input_cols - filter_cols + 2 * padding) // stride) + 1

In [4]:
# Create output feature map
output = np.zeros((output_rows, output_cols), dtype=int)

In [5]:
#b. Slide the filter over the input
for i in range(0, input_rows - filter_rows + 1, stride):
    for j in range(0, input_cols - filter_cols + 1, stride):

        # Extract the current region
        region = input_matrix[
            i:i + filter_rows,
            j:j + filter_cols
        ]

        #c. Compute dot product
        output[i // stride, j // stride] = np.sum(region * filter_matrix)

In [6]:
#d. Print the complete output feature map
print("Output Feature Map:")
print(output)

#e. Print output shape
print("\nOutput Shape:")
print(output.shape)

Output Feature Map:
[[4 3 4]
 [2 4 3]
 [2 3 4]]

Output Shape:
(3, 3)


### f. Changing the stride from 1 to 2 means the filter moves 2 positions at a time instead of 1 position. This reduces the number of times the filter is applied, resulting in a smaller output feature map (2X2).